name: imagekeras_prep_conda_env
channels:
  - defaults
dependencies:
  - python=3.7.11
  - pip=20.0
  - pip:
    - mldesigner
    - kedro[pandas.CSVDataSet]
    - scikit-learn==0.24.1
    - numpy>=1.16.0
    - pandas>=1.2.0
